### ISSUE TITLE
Incompatibility: Permission Viewer breaks the tabbed configure scene view

### ISSUE THREAD

**Issue by dirusulixes** [Rayuaz/twilight-forms#2]
fvtt: 0.8.9
Twilight Forms: 1.0.2
Pin Fixer: 1.1.2

With [Pin Fixer](https://github.com/zeel01/pin-fixer) enabled, the configure scene is borked and unusable
![image](https://user-images.githubusercontent.com/5693623/133662835-9cb555dc-c892-4e7c-982d-e82b4d5e20be.png)

**Comment by dirusulixes** [comment]
I just realised I never posted the error message:

```
jquery.min.js:2 Uncaught DOMException: Failed to execute 'appendChild' on 'Node': The new child element contains the parent.
    at HTMLElement.<anonymous> (https://ros.dirusulixes.site/scripts/jquery.min.js:2:49823)
    at He (https://ros.dirusulixes.site/scripts/jquery.min.js:2:48091)
    at S.fn.init.append (https://ros.dirusulixes.site/scripts/jquery.min.js:2:49724)
    at S.fn.init.S.fn.<computed> [as appendTo] (https://ros.dirusulixes.site/scripts/jquery.min.js:2:51256)
    at HTMLElement.<anonymous> (https://ros.dirusulixes.site/modules/twilight-forms/scripts/form_sections.js:168:21)
    at Function.each (https://ros.dirusulixes.site/scripts/jquery.min.js:2:3003)
    at S.fn.init.each (https://ros.dirusulixes.site/scripts/jquery.min.js:2:1481)
    at form_sectioner (https://ros.dirusulixes.site/modules/twilight-forms/scripts/form_sections.js:144:58)
    at https://ros.dirusulixes.site/modules/twilight-forms/scripts/form_sections.js:6:9
    ```
